### ISSUE TITLE
Cannot write to NFS as root.

### ISSUE THREAD

**Issue by OperationalDev** [adfinis-sygroup/openshift-etcd-backup#23]
In my environment, I cannot write to NFS as root. It would be useful to be able to run commands interacting with NFS as a different user.

See PR: https://github.com/OperationalDev/openshift-etcd-backup/pull/new/sudo_nfs

**Comment by paraenggu** [comment]
Closing issue according to [feedback](https://github.com/adfinis-sygroup/openshift-etcd-backup/pull/22#issuecomment-1063550065) on PR #22
